const id = "EVENT_GTX_ASSIGN_EXTENDED_FONTS";
const name = "Glyph Text: Assign Extended Fonts";
const groups = ["EVENT_GROUP_DIALOGUE"];

const MAX_FONTS = 16;

const autoLabel = (fetchArg) => {
  const n = parseInt(fetchArg("count"), 10) || 0;
  return `Glyph Text: ${n} extended font${n === 1 ? "" : "s"}`;
};

const fields = [].concat(
  [
    {
      type: "label",
      label:
        "Assigns a group of extended fonts to a main font. The main font supplies " +
        "the single-byte characters; anything encoded as a two-byte wide code is " +
        "taken from one of the extended fonts, in the order listed here. Each " +
        "extended font holds up to 64 full-square glyphs. Run this once in the " +
        "first scene's On Init, next to Reset Tile Cache.",
    },
    {
      key: "mainFont",
      label: "Main Font",
      description:
        "The font the wide codes belong to. This should be the project's Default " +
        "Font: the character mapping that produces the wide codes is only applied " +
        "to text compiled with it.",
      type: "font",
      defaultValue: "LAST_FONT",
    },
    {
      key: "count",
      label: "Number Of Extended Fonts",
      description:
        "How many extended fonts make up the group. Glyph codes run through them " +
        "in order: the first font covers the lowest codes, the next carries on " +
        "from there.",
      type: "number",
      min: 1,
      max: MAX_FONTS,
      defaultValue: 1,
    },
    { type: "break" },
  ],
  Array(MAX_FONTS)
    .fill()
    .reduce((arr, _, i) => {
      arr.push({
        key: `font${i}`,
        label: `Extended Font ${i + 1}`,
        type: "font",
        defaultValue: "LAST_FONT",
        conditions: [{ key: "count", gte: i + 1 }],
      });
      return arr;
    }, [])
);

// Each extended font holds up to this many full-square glyphs: a font asset's
// recode table stores one byte per image tile, so it can address at most 256
// deduplicated tiles, and a 16x16 glyph is four of them.
const GLYPHS_PER_FONT = 64;

const compile = (input, helpers) => {
  const { _addComment, _addNL, _stackPushConst, _stackPop, _callNative, writeAsset, options } =
    helpers;
  const { fonts } = options;

  const count = Math.max(1, Math.min(MAX_FONTS, parseInt(input.count, 10) || 1));
  const mainFont = fonts.find((f) => f.id === input.mainFont) ?? fonts[0];
  if (!mainFont) return;

  const chosen = [];
  for (let i = 0; i < count; i++) {
    const font = fonts.find((f) => f.id === input[`font${i}`]);
    if (font) chosen.push(font);
  }
  if (!chosen.length) return;

  // one asset per main font, so two groups in the same project cannot collide
  // (writeAsset is keyed by filename and the later write would win silently)
  const symbol = `gtx_group_${mainFont.symbol}`;

  // byte 0 is the main font this group belongs to, so that switching font
  // mid-text switches its extended fonts with it; byte 1 is the count; then,
  // per font, its index in ui_fonts[] and the span of glyph codes it covers
  const mainIndex = fonts.findIndex((f) => f.id === mainFont.id);
  const rows = chosen.map((font, i) => {
    const index = fonts.findIndex((f) => f.id === font.id);
    const first = i * GLYPHS_PER_FONT;
    return `    ${index}, ${first & 0xff}, ${(first >> 8) & 0xff}, ` +
           `${GLYPHS_PER_FONT & 0xff}, ${(GLYPHS_PER_FONT >> 8) & 0xff},` +
           `   // ${font.name}: glyphs ${first}-${first + GLYPHS_PER_FONT - 1}`;
  });

  writeAsset(
    `${symbol}.c`,
    `#pragma bank 255

// Extended font group for "${mainFont.name}"
// Generated by Glyph Text: Assign Extended Fonts -- do not edit.

#include "gbs_types.h"
#include "data/${symbol}.h"

BANKREF(${symbol})

const UBYTE ${symbol}[] = {
    ${mainIndex},          // the main font this group belongs to
    ${chosen.length},
${rows.join("\n")}
};
`
  );

  writeAsset(
    `${symbol}.h`,
    `#ifndef __${symbol.toUpperCase()}_INCLUDE__
#define __${symbol.toUpperCase()}_INCLUDE__

#include <gbdk/platform.h>
#include "bankdata.h"

BANKREF_EXTERN(${symbol})
extern const UBYTE ${symbol}[];

#endif
`
  );

  _addComment("Glyph Text: Assign Extended Fonts");
  _stackPushConst(`_${symbol}`);
  _stackPushConst(`___bank_${symbol}`);
  _callNative("gtx_set_font_group");
  _stackPop(2);
  _addNL();
};

module.exports = {
  id,
  name,
  autoLabel,
  groups,
  fields,
  compile,
  waitUntilAfterInitFade: false,
};
