#pragma bank 255

// Dynamic Sfx plugin: parameter-driven sound synthesizer.
//
// Replicates the Gen 1 (pokered) cry engine: each sound is three command
// streams (pulse 1, pulse 2, noise) of parameterised hardware notes,
// compiled into ROM data by the "Compile Base Sfx Data" IDE event.
// Per-preset variation comes from two byte modifiers applied at playback
// time:
//   pitch:  added to the 11-bit square frequency and the noise polynomial
//   length: note duration scale, frames = len16 * (0x80 + length) / 256,
//            accumulated in 8.8 fixed point across notes
//
// The player is driven once per frame from a VBL handler (pokered updates
// its audio engine once per VBlank too). While a dynamic sfx plays,
// hardware channels 1, 2 and 4 are taken from the music driver via the
// engine's mute-mask mechanism and handed back when the sound ends.
//
// Stream format (generated by events/eventCompileBaseSfx.js):
//   0x20|len          note; pulse: +env, freq lo, freq hi; noise: +env, poly
//   0xFC, pattern     duty cycle pattern (rotated 2 bits every frame)
//   0xEC, duty        fixed duty cycle (bits 7-6)
//   0xFF              end of channel
//
// Banking: everything lives in the plugin's own switchable bank except two
// small NONBANKED stubs that must be resident in bank 0: the VBL entry
// point and the stream fetch window (see below).

#include <gbdk/platform.h>
#include <stdint.h>

#include "vm.h"
#include "music_manager.h"
#include "sfx_player.h"

#include "dynamic_sfx_player.h"

#define DYNSFX_MUTE_MASK (MUSIC_CH_1 | MUSIC_CH_2 | MUSIC_CH_4)

typedef struct {
    const uint8_t * pc;   // next command; NULL = channel inactive
    uint8_t delay;        // frames until next note (note plays when it hits 1)
    uint8_t frac;         // fractional frame accumulator (8.8 fixed point)
    uint8_t duty_pattern; // rotating 4x2-bit duty pattern
    uint8_t duty;         // current duty bits (7-6)
    uint8_t len6;         // low 6 bits of NRx1 as written at note start
    uint8_t rotate;       // duty pattern rotation enabled
} dynsfx_channel_t;

static dynsfx_channel_t dynsfx_channels[3];
volatile uint8_t dynsfx_active_channels;
static uint16_t dynsfx_tempo;  // 0x80 + length modifier
static uint8_t dynsfx_pitch;
static uint8_t dynsfx_stream_bank;  // ROM bank holding the playing streams
static uint8_t dynsfx_vbl_installed;

// staging window for one stream command: the longest is a pulse note
// (cmd, envelope, freq lo, freq hi)
#define DYNSFX_WINDOW 4
static uint8_t dynsfx_window[DYNSFX_WINDOW];

// ---------------------------------------------------------------------------
// Bank 0 residents
//
// The parser runs from the plugin bank, so it cannot page in the stream bank
// itself. dynsfx_fetch is the one piece that has to stay NONBANKED: it maps
// the stream bank, copies the next command plus its widest possible operand
// set into dynsfx_window, and maps the caller's bank back. Reading up to
// three bytes past a command is harmless, since the extra bytes are only consumed
// once the opcode says they exist.
//
// This deliberately does NOT use MemcpyBanked / ReadBankedUBYTE: every helper
// in the engine's bankdata.c stashes the outgoing bank in one shared static
// (_save) and is documented non-reentrant. We run from the VBL handler while
// the main thread is very likely inside one of them (tile loads, text, scene
// setup), and clobbering _save would leave that caller restoring the wrong
// bank. Keeping the saved bank in a stack local here makes the fetch
// reentrant. The main-thread entry points below have no such constraint and
// use MemcpyBanked.
// ---------------------------------------------------------------------------

void dynsfx_update_banked(void) BANKED;

static void dynsfx_fetch(const uint8_t * pc) NONBANKED {
    uint8_t save_bank = CURRENT_BANK;
    SWITCH_ROM(dynsfx_stream_bank);
    uint8_t * dest = dynsfx_window;
    *dest++ = *pc++;
    *dest++ = *pc++;
    *dest++ = *pc++;
    *dest = *pc;
    SWITCH_ROM(save_bank);
}

void dynsfx_update_isr(void) NONBANKED {
    if (dynsfx_active_channels) dynsfx_update_banked();
}

// ---------------------------------------------------------------------------
// Per-frame update (plugin bank, VBL handler context)
// ---------------------------------------------------------------------------

static void dynsfx_channel_update(uint8_t idx) {
    dynsfx_channel_t * ch = &dynsfx_channels[idx];
    const uint8_t * pc = ch->pc;
    if (!pc) return;

    if (ch->delay != 1) {
        // note still sounding: count down and rotate the duty pattern
        // (delay 0 wraps to 255, matching the original counter behaviour)
        ch->delay--;
        if (ch->rotate) {
            ch->duty_pattern = (uint8_t)((ch->duty_pattern << 2) | (ch->duty_pattern >> 6));
            ch->duty = ch->duty_pattern & 0xC0;
            if (idx == 0) NR11_REG = ch->duty | ch->len6;
            else if (idx == 1) NR21_REG = ch->duty | ch->len6;
        }
        return;
    }

    // fetch commands until a note is played or the stream ends
    for (;;) {
        dynsfx_fetch(pc);
        uint8_t cmd = dynsfx_window[0];
        if (cmd == 0xFF) {  // sound_ret
            ch->pc = NULL;
            dynsfx_active_channels &= ~(1 << idx);
            return;
        }
        if (cmd == 0xFC) {  // duty_cycle_pattern
            ch->duty_pattern = dynsfx_window[1];
            ch->duty = ch->duty_pattern & 0xC0;
            ch->rotate = TRUE;
            pc += 2;
            continue;
        }
        if (cmd == 0xEC) {  // duty_cycle (fixed)
            ch->duty = dynsfx_window[1];
            pc += 2;
            continue;
        }
        // note: low nibble is length-1 in 16ths
        {
            uint16_t d = (uint16_t)((cmd & 0x0F) + 1) * dynsfx_tempo + ch->frac;
            uint8_t env = dynsfx_window[1];
            ch->frac = (uint8_t)d;
            ch->delay = (uint8_t)(d >> 8);
            ch->len6 = ch->delay & 0x3F;
            if (idx == 2) {
                uint8_t poly = dynsfx_window[2] + dynsfx_pitch;
                NR41_REG = ch->len6;
                NR42_REG = env;
                NR43_REG = poly;
                NR44_REG = 0x80;
                pc += 3;
            } else {
                uint16_t freq = dynsfx_window[2] | (((uint16_t)dynsfx_window[3]) << 8);
                freq += dynsfx_pitch;
                if (idx == 0) {
                    NR11_REG = ch->duty | ch->len6;
                    NR12_REG = env;
                    NR13_REG = (uint8_t)freq;
                    NR14_REG = 0x80 | ((freq >> 8) & 0x07);
                } else {
                    NR21_REG = ch->duty | ch->len6;
                    NR22_REG = env;
                    NR23_REG = (uint8_t)freq;
                    NR24_REG = 0x80 | ((freq >> 8) & 0x07);
                }
                pc += 4;
            }
        }
        ch->pc = pc;
        return;
    }
}

void dynsfx_update_banked(void) BANKED {
    // keep the music driver off our channels: the engine resets the mute
    // mask when one of its own sfx streams finishes, so re-assert it
    uint8_t wanted = music_global_mute_mask | music_mute_mask | DYNSFX_MUTE_MASK;
    if (music_effective_mute != wanted) {
        music_effective_mute = driver_set_mute_mask(wanted);
    }

    dynsfx_channel_update(0);
    dynsfx_channel_update(1);
    dynsfx_channel_update(2);

    if (!dynsfx_active_channels) {
        // sound finished: hand channels back (last envelopes ring out unless
        // the music driver immediately writes new notes)
        music_effective_mute = driver_set_mute_mask(music_global_mute_mask | music_mute_mask);
    }
}

// ---------------------------------------------------------------------------
// Control (main thread)
// ---------------------------------------------------------------------------

void dynsfx_play_far(uint8_t bank, const dynsfx_base_t * base, uint8_t pitch, uint8_t length) BANKED {
    // read the three stream pointers out of the data bank before touching
    // anything: this function runs banked, so it cannot page that bank in
    // itself (MemcpyBanked is the engine's NONBANKED cross-bank reader)
    dynsfx_base_t streams;
    MemcpyBanked(&streams, base, sizeof(streams), bank);

    if (!dynsfx_vbl_installed) {
        dynsfx_vbl_installed = TRUE;
        CRITICAL {
            add_VBL(dynsfx_update_isr);
        }
    }

    CRITICAL {
        dynsfx_channels[0].pc = streams.pulse1;
        dynsfx_channels[1].pc = streams.pulse2;
        dynsfx_channels[2].pc = streams.noise;
        dynsfx_stream_bank = bank;

        for (uint8_t i = 0; i < 3; i++) {
            dynsfx_channels[i].delay = 1;  // first note plays on the next frame
            dynsfx_channels[i].frac = 0;
            dynsfx_channels[i].duty_pattern = 0;
            dynsfx_channels[i].duty = 0;
            dynsfx_channels[i].len6 = 0;
            dynsfx_channels[i].rotate = FALSE;
        }
        dynsfx_pitch = pitch;
        dynsfx_tempo = 0x80 + length;

        // silence whatever the music driver left on our channels and mute it
        sfx_sound_cut_mask(DYNSFX_MUTE_MASK);
        NR10_REG = 0x08;  // no sweep (pokered idle sweep value)
        dynsfx_active_channels = 0x07;
        music_effective_mute = driver_set_mute_mask(music_global_mute_mask | music_mute_mask | DYNSFX_MUTE_MASK);
    }
}

void dynsfx_stop(void) BANKED {
    CRITICAL {
        if (dynsfx_active_channels) {
            dynsfx_active_channels = 0;
            dynsfx_channels[0].pc = dynsfx_channels[1].pc = dynsfx_channels[2].pc = NULL;
            sfx_sound_cut_mask(DYNSFX_MUTE_MASK);
            music_effective_mute = driver_set_mute_mask(music_global_mute_mask | music_mute_mask);
        }
    }
}

// ---------------------------------------------------------------------------
// VM natives
// ---------------------------------------------------------------------------

void vm_dynsfx_play_data(SCRIPT_CTX * THIS) OLDCALL BANKED {
    // pushed in order: pitch, length, addr, bank -> FN_ARG0 = bank (last pushed)
    uint16_t bank   = *(uint16_t *)VM_REF_TO_PTR(FN_ARG0);
    uint16_t addr   = *(uint16_t *)VM_REF_TO_PTR(FN_ARG1);
    uint16_t length = *(uint16_t *)VM_REF_TO_PTR(FN_ARG2);
    uint16_t pitch  = *(uint16_t *)VM_REF_TO_PTR(FN_ARG3);
    dynsfx_play_far((uint8_t)bank, (const dynsfx_base_t *)addr, (uint8_t)pitch, (uint8_t)length);
}

void vm_dynsfx_play_preset_data(SCRIPT_CTX * THIS) OLDCALL BANKED {
    // pushed in order: addr, bank -> FN_ARG0 = bank (last pushed)
    uint16_t bank = *(uint16_t *)VM_REF_TO_PTR(FN_ARG0);
    uint16_t addr = *(uint16_t *)VM_REF_TO_PTR(FN_ARG1);
    dynsfx_preset_def_t def;
    MemcpyBanked(&def, (const void *)addr, sizeof(def), (uint8_t)bank);
    dynsfx_play_far(def.base.bank, (const dynsfx_base_t *)def.base.ptr, def.pitch, def.length);
}

void vm_dynsfx_stop(SCRIPT_CTX * THIS) OLDCALL BANKED {
    (void)THIS;
    dynsfx_stop();
}

UBYTE vm_dynsfx_wait(void * THIS, UBYTE start, UWORD * stack_frame) OLDCALL BANKED {
    (void)start; (void)stack_frame;
    if (dynsfx_active_channels) {
        ((SCRIPT_CTX *)THIS)->waitable = TRUE;
        return FALSE;
    }
    return TRUE;
}
